# Generated by Django 6.1 on 2026-08-14 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Dresses', 'Dresses'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], default='Tops', max_length=20)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('season', models.CharField(choices=[('All', 'All'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Fall', 'Fall'), ('Spring', 'Spring')], default='All', max_length=20)),
                ('occasion', models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Party', 'Party'), ('Workout', 'Workout'), ('Work', 'Work')], default='Casual', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe_items/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('times_worn', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
